import { PluginFunction, Types } from '@graphql-codegen/plugin-helpers';
import { transformSchemaAST } from '@graphql-codegen/schema-ast';
import { GraphQLSchema } from 'graphql';
import { FlutterFreezedClassPluginConfig } from './config';

export const plugin: PluginFunction<Partial<FlutterFreezedClassPluginConfig>, Types.ComplexPluginOutput> = (
  schema: GraphQLSchema,
  documents: Types.DocumentFile[],
  config: FlutterFreezedClassPluginConfig
) => {
  // return `// The following codes were generated by FlutterFreezedClass Plugin`

  const { schema: _schema, ast } = transformSchemaAST(schema, config);

  return { prepend: [], content: '' };
};
